In [5]:
import numpy as np

In [6]:
import tensorflow as tf

In [12]:
# Define a 2D tensor
tensor = tf.constant([[5, 2, 3], [4, 5, 6]])
print(tensor.numpy())
# Find the index of the maximum value along axis 0
argmax_indices = tf.argmax(tensor, axis=0)
print(argmax_indices.numpy()) # [1 1 1]

# Find the maximum value along axis 0
max_values = tf.reduce_max(tensor, axis=0)
print(max_values.numpy()) # [4 5 6]

[[5 2 3]
 [4 5 6]]
[0 1 1]
[5 5 6]
